### PR TITLE
Adding incomplete examples. 

### PR DESCRIPTION
**Pull request by SoniyaKiran**
In this PR, two examples are added, One is for merging multiple instances of the same module (examples 06)  and the other is for creating multiple feedthroughs from instance  and reusing them on other instance of the same module(example 07).

### CODE REVIEW

**Comment by ganeshgore** [comment]
@SoniyaKiran This looks good already, do not worry about the CI; for now, I am doing some experiments.

If you are done with this example, please remove the [WIP] tag from the title and good descriptions of what your trying to merge in this PR (to learn good practices of GitHub collaboration)

**Comment by ganeshgore** [comment]
Please add images in the docstring (on top of the script) please check other scripts in the same directory for example.

**Comment by SoniyaKiran** [comment]
I have pushed the edited files, having the images in the docstring.

**Comment by ganeshgore** [comment]
Don't add SVG files to PR, make .svg file names start with _ (underscroll), we generate SVG file again on the CI

**Comment by ganeshgore** [comment]
You will also have to change the name in docstring otherwise, it will not render

**Comment by ganeshgore** [comment]
Looks good, congratulations to your first contribution to SpyDrNet-Physical

**Pull request merged**
